id: D1C97EDC9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T08:32:04+00:00'
last_modified: '2022-05-30T07:40:40.479470+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    55ed:
      image_group_id: I1PD95892
      title: ཁྲོ་བོ་རེག་ཚིག་གི་སྦྱིན་སྲེག་གི་ཆོ་ག།
      total_pages: 1464
      order: 47
      base_file: 55ed.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
