id: P75A96D0B
initial_creation_type: ocr
source_metadata:
  volumes:
    627fc40e53f043f5bac844d88325fe35:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ཁྲོ་བོ་རེག་ཚིག་གི་སྦྱིན་སྲེག་གི་ཆོ་ག།
      total_pages: 1464
      volume_number: 47
